ARG CORE_IMAGE=chembience/core-jupyter:latest
FROM ${CORE_IMAGE}

COPY app-requirements.txt /jupyter/app-requirements.txt

RUN if grep -qE '^\s*[^#\s]' /jupyter/app-requirements.txt; then \
        micromamba run -n chembience python -m pip install --no-cache-dir -r /jupyter/app-requirements.txt; \
    else \
        echo "requirements.txt is empty; skipping pip install"; \
    fi && \
    micromamba clean -a -y && \
    find /opt/conda/ -follow -type f -name '*.a' -delete && \
    find /opt/conda/ -follow -type f -name '*.pyc' -delete && \
    find /opt/conda/ -follow -type f -name '*.js.map' -delete

COPY notebooks /home/app/notebooks

WORKDIR /home/app
