apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chembience.appConfigName" . }}
  labels:
    {{- include "chembience.labels" . | nindent 4 }}
data:
  CHEMBIENCE_RUNTIME_MODE: "prod"
  POSTGRES_HOST: {{ include "chembience.postgresHost" . | quote }}
  POSTGRES_PORT: "5432"
  POSTGRES_INTERNAL_PORT: "5432"
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_NAME: {{ .Values.postgres.database | quote }}
  {{- if eq .Values.app.kind "django" }}
  DJANGO_SETTINGS_MODULE: "chembience.django_prod_settings"
  DJANGO_VIRTUAL_HOSTNAME: {{ .Values.django.virtualHostname | quote }}
  DJANGO_CSRF_TRUSTED_ORIGINS: {{ .Values.django.csrfTrustedOrigins | quote }}
  DJANGO_TRUST_X_FORWARDED_PROTO: {{ .Values.django.trustXForwardedProto | quote }}
  {{- end }}
  {{- range $key, $value := .Values.app.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
