#!/bin/bash
set -e

CHEMBIENCE_UID="${CHEMBIENCE_UID:-1000}"
CHEMBIENCE_GID="${CHEMBIENCE_GID:-1000}"

# Pick a group to use:
# - Prefer an existing "app" group
# - Else, if the requested GID already exists, reuse that group's name
# - Else, create "app" with the requested GID
if ! getent group app >/dev/null 2>&1; then
    if getent group "${CHEMBIENCE_GID}" >/dev/null 2>&1; then
        # A group with this GID already exists — reuse its name rather than
        # creating a duplicate; the user 'app' will be bound to it below.
        APP_GROUP="$(getent group "${CHEMBIENCE_GID}" | cut -d: -f1)"
        echo "✅ Group with GID $CHEMBIENCE_GID already exists: $APP_GROUP"
    else
        echo "➕ Creating group 'app' with GID $CHEMBIENCE_GID..."
        groupadd -g "${CHEMBIENCE_GID}" app
        APP_GROUP="app"
    fi
else
    APP_GROUP="app"
    echo "✅ Group 'app' already exists."
fi

if ! id "app" >/dev/null 2>&1; then
    echo "➕ Creating user 'app' with UID $CHEMBIENCE_UID and group $APP_GROUP..."
    useradd --shell /bin/bash -u "${CHEMBIENCE_UID}" -g "${APP_GROUP}" -o -c "" -M app
else
    echo "✅ User 'app' already exists."
fi

id app >/dev/null 2>&1

# Ensure correct ownership and permissions for /home/app.
# Selective chown to avoid a slow full -R sweep on large bind-mounted volumes.
echo "🔧 Ensuring correct ownership of /home/app..."
fix_ownership() {
    find /home/app -not -user app -print0 2>/dev/null \
        | xargs -0 -r chown "app:$APP_GROUP" 2>/dev/null || true
}
cleanup_ownership() {
    echo "🧹 Finalizing ownership of /home/app..."
    fix_ownership
}
trap cleanup_ownership EXIT

fix_ownership

# Helpers ---------------------------------------------------------------------
# sync_config: copy a baked-in config file into APP_HOME only if missing.
# Refresh a ".dist" sibling so users can diff against the shipped version.
sync_config() {
    src="$1"; dst="$2"
    [ -f "$src" ] || return 0
    if [ ! -f "$dst" ]; then
        cp "$src" "$dst"
        sed -i 's/\r$//' "$dst" 2>/dev/null || true
    fi
    cp "$src" "${dst}.dist"
    sed -i 's/\r$//' "${dst}.dist" 2>/dev/null || true
}

# sync_script: always refresh helper scripts, strip CRLF, mark executable.
sync_script() {
    src="$1"; dst="$2"
    [ -f "$src" ] || return 0
    cp "$src" "$dst"
    chmod +x "$dst"
    sed -i 's/\r$//' "$dst"
}

echo "📄 Syncing internal configuration files to /home/app..."
sync_config "/jupyter/docker-compose.yml"    "/home/app/docker-compose.yml"
sync_config "/jupyter/Dockerfile"            "/home/app/Dockerfile"
sync_config "/jupyter/requirements.txt"      "/home/app/requirements.txt"
sync_config "/jupyter/app-requirements.txt"  "/home/app/app-requirements.txt"
sync_config "/jupyter/README.md"             "/home/app/README.md"
sync_script "/jupyter/psql"                  "/home/app/psql"
sync_script "/jupyter/jupyter-init"          "/home/app/jupyter-init"
sync_script "/jupyter/jupyter-configure"      "/home/app/jupyter-configure"
[ -f "/.gitignore" ] && cp "/.gitignore" "/home/app/.gitignore"

# Create/reconcile the per-app .env (source of truth for this app)
ensure_kv() {
    # ensure_kv FILE VAR VALUE  -> append VAR=VALUE if VAR is missing in FILE
    local file="$1" var="$2" val="$3"
    if ! grep -E "^${var}=" "$file" >/dev/null 2>&1; then
        echo "${var}=${val}" >>"$file"
    fi
}

if [ ! -f "/home/app/.env" ]; then
    echo "📝 Creating minimal .env for Jupyter in /home/app..."
    {
        echo "# ⚠️ AUTO-GENERATED FILE - INITIAL TEMPLATE"
        echo "# Generated by Chembience Jupyter entrypoint"
        echo ""
        echo "CHEMBIENCE_VERSION=${CHEMBIENCE_VERSION:-latest}"
        echo "CHEMBIENCE_IMAGE_TAG=${CHEMBIENCE_VERSION:-latest}"
        echo "APP_NAME=${APP_NAME:--app}"
        echo "APP_HOME=."
        echo "CHEMBIENCE_UID=${CHEMBIENCE_UID}"
        echo "CHEMBIENCE_GID=${CHEMBIENCE_GID}"
        echo "JUPYTER_CONNECTION_PORT=${JUPYTER_CONNECTION_PORT:-8888}"
        echo "POSTGRES_USER=${POSTGRES_USER:-chembience}"
        echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
        echo "POSTGRES_NAME=${POSTGRES_NAME:-chembience}"
        echo "POSTGRES_HOST=${POSTGRES_HOST:-postgres}"
        echo "POSTGRES_PORT=${POSTGRES_PORT:-5433}"
    } > "/home/app/.env"

    # Persist a pinned Jupyter token if provided on first init
    if [ -n "${JUPYTER_TOKEN}" ]; then
        echo "JUPYTER_TOKEN=${JUPYTER_TOKEN}" >> "/home/app/.env"
    fi

    # Ensure LF line endings
    sed -i 's/\r$//' "/home/app/.env"
else
    # Non-destructive reconciliation: ensure critical keys exist
    echo "🔁 Reconciling required keys in existing .env..."
    ensure_kv "/home/app/.env" "JUPYTER_CONNECTION_PORT" "${JUPYTER_CONNECTION_PORT:-8888}"
    # If a token is provided via env and not present in .env, add it to persist across restarts
    if [ -n "${JUPYTER_TOKEN}" ]; then
        ensure_kv "/home/app/.env" "JUPYTER_TOKEN" "${JUPYTER_TOKEN}"
    fi
fi

# Sync app if it exists in /jupyter/app
if [ -d "/jupyter/app/notebooks" ] && [ ! -d "/home/app/notebooks" ]; then
    echo "📄 Syncing notebooks to /home/app/notebooks..."
    cp -r "/jupyter/app/notebooks" "/home/app/notebooks"
fi

# Final ownership check
fix_ownership

exec gosu app "$@"
