#!/bin/bash
set -e

CHEMBIENCE_UID="${CHEMBIENCE_UID:-1000}"
CHEMBIENCE_GID="${CHEMBIENCE_GID:-1000}"

# Pick a group to use:
# - Prefer an existing "app" group
# - Else, if the requested GID already exists, reuse that group's name
# - Else, create "app" with the requested GID
if ! getent group app >/dev/null 2>&1; then
    if getent group "${CHEMBIENCE_GID}" >/dev/null 2>&1; then
        # A group with this GID already exists — reuse its name rather than
        # creating a duplicate; the user 'app' will be bound to it below.
        APP_GROUP="$(getent group "${CHEMBIENCE_GID}" | cut -d: -f1)"
        echo "✅ Group with GID $CHEMBIENCE_GID already exists: $APP_GROUP"
    else
        echo "➕ Creating group 'app' with GID $CHEMBIENCE_GID..."
        groupadd -g "${CHEMBIENCE_GID}" app
        APP_GROUP="app"
    fi
else
    APP_GROUP="app"
    echo "✅ Group 'app' already exists."
fi

if ! id "app" >/dev/null 2>&1; then
    echo "➕ Creating user 'app' with UID $CHEMBIENCE_UID and group $APP_GROUP..."
    useradd --shell /bin/bash -u "${CHEMBIENCE_UID}" -g "${APP_GROUP}" -o -c "" -M app
else
    echo "✅ User 'app' already exists."
fi

id app >/dev/null 2>&1

# Ensure correct ownership and permissions for /home/app.
# Selective chown to avoid a slow full -R sweep on large bind-mounted volumes.
echo "🔧 Ensuring correct ownership of /home/app..."
fix_ownership() {
    find /home/app -not -user app -print0 2>/dev/null \
        | xargs -0 -r chown "app:$APP_GROUP" 2>/dev/null || true
}
cleanup_ownership() {
    echo "🧹 Finalizing ownership of /home/app..."
    fix_ownership
}
trap cleanup_ownership EXIT

fix_ownership

# Helpers ---------------------------------------------------------------------
# sync_config: copy a baked-in config file into APP_HOME only if missing.
# User edits on the bind mount are preserved; a ".dist" copy is always
# refreshed so users can diff against the latest shipped version.
sync_config() {
    src="$1"; dst="$2"
    [ -f "$src" ] || return 0
    if [ ! -f "$dst" ]; then
        cp "$src" "$dst"
        sed -i 's/\r$//' "$dst" 2>/dev/null || true
    fi
    cp "$src" "${dst}.dist"
    sed -i 's/\r$//' "${dst}.dist" 2>/dev/null || true
}

# sync_script: always refresh helper scripts, strip CRLF, mark executable.
sync_script() {
    src="$1"; dst="$2"
    [ -f "$src" ] || return 0
    cp "$src" "$dst"
    chmod +x "$dst"
    sed -i 's/\r$//' "$dst"
}

echo "📄 Syncing internal configuration files to /home/app..."
sync_config "/fastapi/docker-compose.yml"          "/home/app/docker-compose.yml"
sync_config "/fastapi/docker-compose.override.yml" "/home/app/docker-compose.override.yml"
sync_config "/fastapi/Dockerfile"                  "/home/app/Dockerfile"
sync_config "/fastapi/requirements.txt"            "/home/app/requirements.txt"
sync_config "/fastapi/README.md"                   "/home/app/README.md"
sync_script "/fastapi/psql"                        "/home/app/psql"
sync_script "/fastapi/db_backup"                   "/home/app/db_backup"
sync_script "/fastapi/db_restore"                  "/home/app/db_restore"
sync_script "/fastapi/db_cleanup"                  "/home/app/db_cleanup"
# fastapi-init is now expected to be in /fastapi/fastapi-init (synced from fastapi/app/fastapi-init in Dockerfile)
sync_script "/fastapi/fastapi-init"                "/home/app/fastapi-init"
sync_script "/fastapi/fastapi-configure"           "/home/app/fastapi-configure"
[ -f "/.gitignore" ] && cp "/.gitignore" "/home/app/.gitignore"
[ -f "/.gitattributes" ] && cp "/.gitattributes" "/home/app/.gitattributes"
if [ -f "/home/app/.gitignore" ]; then
    if ! grep -Eq "^postgres/?([[:space:]]|#|$)" "/home/app/.gitignore"; then
        echo "" >> "/home/app/.gitignore"
        echo "# Added by entrypoint" >> "/home/app/.gitignore"
        echo "postgres/" >> "/home/app/.gitignore"
    fi
fi

# Create/reconcile the per-app .env (source of truth for this app)
ensure_kv() {
    # ensure_kv FILE VAR VALUE  -> append VAR=VALUE if VAR is missing in FILE
    local file="$1" var="$2" val="$3"
    if ! grep -E "^${var}=" "$file" >/dev/null 2>&1; then
        echo "${var}=${val}" >>"$file"
    fi
}

if [ ! -f "/home/app/.env" ]; then
    echo "📝 Creating minimal .env for FastAPI in /home/app..."
    {
        echo "# ⚠️ AUTO-GENERATED FILE - INITIAL TEMPLATE"
        echo "# Generated by Chembience FastAPI entrypoint"
        echo ""
        echo "CHEMBIENCE_VERSION=${CHEMBIENCE_VERSION:-latest}"
        echo "CHEMBIENCE_IMAGE_TAG=${CHEMBIENCE_VERSION:-latest}"
        echo "APP_NAME=${APP_NAME:-app}"
        echo "APP_HOME=."
        echo "CHEMBIENCE_UID=${CHEMBIENCE_UID}"
        echo "CHEMBIENCE_GID=${CHEMBIENCE_GID}"
        echo "FASTAPI_CONNECTION_PORT=${FASTAPI_CONNECTION_PORT:-8002}"
        echo "POSTGRES_USER=${POSTGRES_USER:-chembience}"
        echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
        echo "POSTGRES_NAME=${POSTGRES_NAME:-chembience}"
        echo "POSTGRES_HOST=${POSTGRES_HOST:-postgres}"
        echo "POSTGRES_PORT=${POSTGRES_PORT:-5433}"
    } > "/home/app/.env"

    # Ensure LF line endings for .env
    sed -i 's/\r$//' "/home/app/.env"
else
    # Non-destructive reconciliation: ensure critical keys exist
    echo "🔁 Reconciling required keys in existing .env..."
    ensure_kv "/home/app/.env" "FASTAPI_CONNECTION_PORT" "${FASTAPI_CONNECTION_PORT:-8002}"
fi

# Ensure all synced files have correct ownership
fix_ownership

# Sync src from the image into the bind-mounted /home/app.
# The host bind mount (${APP_HOME}:/home/app) shadows the src/ baked into
# the image, so we must materialize it here on every start. We only copy files
# that don't already exist in the target so user edits are preserved across
# restarts, but missing files (e.g. main.py on a freshly created APP_HOME) are
# always restored — otherwise uvicorn fails with "Could not import module main".
if [ -d "/fastapi/src" ]; then
    echo "📄 Syncing src to /home/app/src (preserving existing files)..."
    mkdir -p /home/app/src
    cp -rn /fastapi/src/. /home/app/src/

    # Ensure LF line endings for src files
    find /home/app/src -type f -name "*.py" -exec sed -i 's/\r$//' {} +
fi

# Final ownership check
fix_ownership

# Clean up legacy directories if they exist (renamed to src)
for legacy in "/home/app/appsite" "/home/app/apisite" "/home/app/app"; do
    if [ -d "$legacy" ]; then
        echo "🧹 Removing legacy directory: $legacy..."
        rm -rf "$legacy"
    fi
done

exec gosu app "$@"
