apiVersion: v2
name: chembience
description: Shared Helm chart base for immutable Chembience applications with RDKit PostgreSQL
type: application
version: 0.1.0
appVersion: "0.6.2"
kubeVersion: ">=1.25.0-0"
keywords:
  - chembience
  - rdkit
  - postgresql
  - cheminformatics
