#!/bin/bash
set -e

CHEMBIENCE_UID="${CHEMBIENCE_UID:-1000}"
CHEMBIENCE_GID="${CHEMBIENCE_GID:-1000}"

# Pick a group to use:
# - Prefer an existing "app" group
# - Else, if the requested GID already exists, reuse that group's name
# - Else, create "app" with the requested GID
if ! getent group app >/dev/null 2>&1; then
    if getent group "${CHEMBIENCE_GID}" >/dev/null 2>&1; then
        # A group with this GID already exists — reuse its name rather than
        # creating a duplicate; the user 'app' will be bound to it below.
        APP_GROUP="$(getent group "${CHEMBIENCE_GID}" | cut -d: -f1)"
        echo "✅ Group with GID $CHEMBIENCE_GID already exists: $APP_GROUP"
    else
        echo "➕ Creating group 'app' with GID $CHEMBIENCE_GID..."
        groupadd -g "${CHEMBIENCE_GID}" app
        APP_GROUP="app"
    fi
else
    APP_GROUP="app"
    echo "✅ Group 'app' already exists."
fi

# Create user if missing (bind it to the chosen group)
if ! id "app" >/dev/null 2>&1; then
    echo "➕ Creating user 'app' with UID $CHEMBIENCE_UID and group $APP_GROUP..."
    useradd --shell /bin/bash -u "${CHEMBIENCE_UID}" -g "${APP_GROUP}" -o -c "" -M app
else
    echo "✅ User 'app' already exists."
fi

# Safety check: don't try gosu if user still doesn't exist
id app >/dev/null 2>&1

# Helpers ---------------------------------------------------------------------
# sync_config: copy a baked-in config file into APP_HOME only if it does NOT
# already exist there. User edits on the bind mount are preserved across
# restarts; missing files are restored.
sync_config() {
    src="$1"; dst="$2"
    [ -f "$src" ] || return 0
    if [ ! -f "$dst" ]; then
        cp "$src" "$dst"
        sed -i 's/\r$//' "$dst" 2>/dev/null || true
    fi
}

# sync_script: copy helper scripts into APP_HOME only if missing.
sync_script() {
    src="$1"; dst="$2"
    [ -f "$src" ] || return 0
    if [ ! -f "$dst" ]; then
        cp "$src" "$dst"
        chmod +x "$dst"
        sed -i 's/\r$//' "$dst"
    fi
}

export PYTHONPATH=/home/app:/share:$PYTHONPATH

# Initialize app context if missing or if it looks like a django app
if [ ! -f "/home/app/.rdkit-init" ] || [ -d "/home/app/src" ]; then
    # ONLY initialize if we are NOT in a django container.
    # We can check for existence of /django (copied in django/Dockerfile)
    if [ -d "/django" ]; then
        echo "✅ Django container detected, skipping rdkit initialization."
    else
        echo "🚀 Initializing /home/app for rdkit app..."
        sync_script "/opt/rdkit/run"             "/home/app/run"
        sync_script "/opt/rdkit/shell"           "/home/app/shell"
        sync_script "/opt/rdkit/rdkit-init"      "/home/app/rdkit-init"
        sync_script "/opt/rdkit/rdkit-configure" "/home/app/rdkit-configure"
        sync_script "/opt/rdkit/psql"            "/home/app/psql"
        
        sync_config "/opt/rdkit/docker-compose.yml" "/home/app/docker-compose.yml"
        sync_config "/opt/rdkit/Dockerfile"         "/home/app/Dockerfile"
        sync_config "/opt/rdkit/README.md"          "/home/app/README.md"
        
        [ -f "/.gitignore" ] && [ ! -f "/home/app/.gitignore" ] && cp "/.gitignore" "/home/app/.gitignore"
        [ -f "/.dockerignore" ] && [ ! -f "/home/app/.dockerignore" ] && cp "/.dockerignore" "/home/app/.dockerignore"
        [ -f "/.gitattributes" ] && [ ! -f "/home/app/.gitattributes" ] && cp "/.gitattributes" "/home/app/.gitattributes"
        if [ -f "/home/app/.gitignore" ]; then
            if ! grep -Eq "^postgres/postgres_data/?([[:space:]]|#|$)" "/home/app/.gitignore"; then
                echo "" >> "/home/app/.gitignore"
                echo "# Added by entrypoint" >> "/home/app/.gitignore"
                echo "postgres/postgres_data" >> "/home/app/.gitignore"
            fi
        fi
        if [ -f "/home/app/.dockerignore" ]; then
            if ! grep -Eq "^postgres/postgres_data/?([[:space:]]|#|$)" "/home/app/.dockerignore"; then
                echo "" >> "/home/app/.dockerignore"
                echo "# Added by entrypoint" >> "/home/app/.dockerignore"
                echo "postgres/postgres_data" >> "/home/app/.dockerignore"
            fi
        fi
        
    # Create .env file in /home/app
    if [ ! -f "/home/app/.env" ]; then
        echo "📝 Creating .env file in /home/app..."
        {
            echo "# ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY IF YOU WANT TO PERSIST CHANGES"
            echo "# This file was generated by the Chembience initialization script."
            echo ""
            echo "CHEMBIENCE_VERSION=${CHEMBIENCE_VERSION:-latest}"
            echo "CHEMBIENCE_IMAGE_TAG=${CHEMBIENCE_VERSION:-latest}"
            echo "APP_NAME=${APP_NAME:-app}"
            echo "APP_HOME=."
            echo "CHEMBIENCE_UID=${CHEMBIENCE_UID}"
            echo "CHEMBIENCE_GID=${CHEMBIENCE_GID}"
            echo "POSTGRES_USER=${POSTGRES_USER:-chembience}"
            echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
            echo "POSTGRES_NAME=${POSTGRES_NAME:-chembience}"
            echo "POSTGRES_HOST=${POSTGRES_HOST:-postgres}"
            echo "POSTGRES_PORT=\${POSTGRES_PORT:-5433}"
        } > /home/app/.env
        
        # Ensure LF line endings
        sed -i 's/\r$//' "/home/app/.env"
    fi

        # Finalize
        touch /home/app/.rdkit-init
    fi
fi

if [ ! -f "/home/app/requirements.txt" ]; then
    cp /opt/rdkit/app-requirements.txt /home/app/requirements.txt
fi

# Ensure all files in /home/app are owned by the app user (selective).
find /home/app -not -user app -print0 2>/dev/null \
    | xargs -0 -r chown "app:${APP_GROUP}" 2>/dev/null || true

exec gosu app "$@"

