#!/bin/bash
set -e

CHEMBIENCE_UID="${CHEMBIENCE_UID:-1000}"
CHEMBIENCE_GID="${CHEMBIENCE_GID:-1000}"

# Pick a group to use:
# - Prefer an existing "app" group
# - Else, if the requested GID already exists, reuse that group's name
# - Else, create "app" with the requested GID
if ! getent group app >/dev/null 2>&1; then
    if getent group "${CHEMBIENCE_GID}" >/dev/null 2>&1; then
        # A group with this GID already exists — reuse its name rather than
        # creating a duplicate; the user 'app' will be bound to it below.
        APP_GROUP="$(getent group "${CHEMBIENCE_GID}" | cut -d: -f1)"
        echo "✅ Group with GID $CHEMBIENCE_GID already exists: $APP_GROUP"
    else
        echo "➕ Creating group 'app' with GID $CHEMBIENCE_GID..."
        groupadd -g "${CHEMBIENCE_GID}" app
        APP_GROUP="app"
    fi
else
    APP_GROUP="app"
    echo "✅ Group 'app' already exists."
fi

# Create user if missing (bind it to the chosen group)
if ! id "app" >/dev/null 2>&1; then
    echo "➕ Creating user 'app' with UID $CHEMBIENCE_UID and group $APP_GROUP..."
    useradd --shell /bin/bash -u "${CHEMBIENCE_UID}" -g "${APP_GROUP}" -o -c "" -M app
else
    echo "✅ User 'app' already exists."
fi

# Safety check: don't try gosu if user still doesn't exist
id app >/dev/null 2>&1

export PYTHONPATH=/home/app:/share:$PYTHONPATH

# Initialize app context if missing or if it looks like a django app
if [ ! -f "/home/app/.rdkit-init" ] || [ -d "/home/app/src" ]; then
    # ONLY initialize if we are NOT in a django container.
    # We can check for existence of /django (copied in django/Dockerfile)
    if [ -d "/django" ]; then
        echo "✅ Django container detected, skipping rdkit initialization."
    else
        echo "🚀 Initializing /home/app for rdkit app..."
        cp /opt/rdkit/run /home/app/run
        cp /opt/rdkit/shell /home/app/shell
        cp /opt/rdkit/rdkit-init /home/app/rdkit-init
        cp /opt/rdkit/rdkit-configure /home/app/rdkit-configure
        cp /opt/rdkit/psql /home/app/psql
        cp /opt/rdkit/docker-compose.yml /home/app/docker-compose.yml
        cp /opt/rdkit/Dockerfile /home/app/Dockerfile
        cp /opt/rdkit/README.md /home/app/README.md
        
    # Create .env file in /home/app
    if [ ! -f "/home/app/.env" ]; then
        echo "📝 Creating .env file in /home/app..."
        {
            echo "# ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY IF YOU WANT TO PERSIST CHANGES"
            echo "# This file was generated by the Chembience initialization script."
            echo ""
            echo "CHEMBIENCE_VERSION=${CHEMBIENCE_VERSION:-latest}"
            echo "CHEMBIENCE_IMAGE_TAG=${CHEMBIENCE_VERSION:-latest}"
            echo "APP_NAME=${APP_NAME:--app}"
            echo "APP_HOME=."
            echo "CHEMBIENCE_UID=${CHEMBIENCE_UID}"
            echo "CHEMBIENCE_GID=${CHEMBIENCE_GID}"
            echo "POSTGRES_USER=${POSTGRES_USER:-chembience}"
            echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
            echo "POSTGRES_NAME=${POSTGRES_NAME:-chembience}"
            echo "POSTGRES_HOST=${POSTGRES_HOST:-postgres}"
            echo "POSTGRES_PORT=\${POSTGRES_PORT:-5433}"
        } > /home/app/.env
        
        # Ensure LF line endings
        sed -i 's/\r$//' "/home/app/.env"
    fi

        chmod +x /home/app/run /home/app/shell /home/app/rdkit-init /home/app/rdkit-configure /home/app/psql
        
        # Clean up django-specific files if they exist
        rm -rf /home/app/appsite /home/app/apisite /home/app/src /home/app/django-init /home/app/django-manage-py
        
        touch /home/app/.rdkit-init
    fi
fi

if [ ! -f "/home/app/requirements.txt" ]; then
    cp /opt/rdkit/app-requirements.txt /home/app/requirements.txt
fi

# Ensure all files in /home/app are owned by the app user (selective).
find /home/app -not -user app -print0 2>/dev/null \
    | xargs -0 -r chown "app:${APP_GROUP}" 2>/dev/null || true

exec gosu app "$@"

